### PR TITLE
Override puts method to use Trump's nicknames for other candidates

### PR DESCRIPTION
**Pull request by trliner**
Trump has a penchant for giving other candidates [cute little nicknames](http://archive.is/2016.08.24-015831/http://abcnews.go.com/Politics/crooked-hillary-marco-donald-trumps-nicknames/story?id=39035114). This feature will automatically replace those candidates' names with their corresponding nicknames.

### CODE REVIEW

**Comment by rickr** [comment]
Hey @trliner - thanks for the commit!

Can you just verify that you're from the US? I'm not racist. In fact I am the least racist person. I just want to make sure we don't take pull requests away from US citizens that may need them.

**Comment by ErikWPE** [comment]
@rickr, I can confirm that @trliner is from the US.

**Comment by trliner** [comment]
@rickr I completely understand. I'm probably the most patriotic person I know. US pull requests first!

Thanks @ErikWPE for the reference. I have the most fantastic references, don't I, folks?

I'm going to show you so much proof that I'm in the US. It's going to blow your mind. Believe me! 

There's going to be so much proof that I'm in the US that you're going to say: @trliner I'm _tired_ of seeing proof that you're in the US.

Now while I'm gathering all that proof, you should merge this pull request. It really is the best pull request!

**Comment by rickr** [comment]
@trliner thank you for being a truly patriotic American.

**Pull request merged**
